import React from "react";
import Strengths from "./analytic/Strengths";
import Weakness from "./analytic/Weakness";
import Recommendation from "./analytic/Recommendation";
import Summary from "./analytic/Summary";

export default function AnalyticResponse({
  strengths,
  weakness,
  recommendations,
  summary,
  onDetail,
}: {
  strengths: string[];
  weakness: string[];
  recommendations: string[];
  summary: string;
  onDetail: () => void;
}) {
  return (
    <div className="w-full p-4 sm:p-6 text-white bg-gradient-to-b from-gray-800 to-blue-700">
      {/* Header */}
      <div className="mb-6 sm:mb-8">
        <h1 className="text-3xl sm:text-5xl lg:text-6xl font-extrabold text-center mb-3 sm:mb-4">
          <span className="bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 bg-clip-text text-transparent drop-shadow-lg tracking-tight">
            Learning Analytics Report
          </span>
        </h1>
        <div className="h-1 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 rounded-full mx-auto w-20 sm:w-32"></div>
      </div>

      {/* Three Column Layout */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
        {/* Strengths */}
        <Strengths strengths={strengths} />

        {/* Weaknesses */}
        <Weakness weakness={weakness} />

        {/* Recommendations */}
        <Recommendation recommendations={recommendations} />
      </div>
      {/* Summary Section */}
      <div className="mt-6 sm:mt-8">
        <Summary summary={summary} />
      </div>

      {/* Footer */}
      <div className="mt-6 sm:mt-8 text-center">
        <div>
          <button
            onClick={onDetail}
            className="my-2 mx-2 px-4 py-2 sm:px-6 sm:py-2 bg-gradient-to-r from-blue-500 to-purple-500 text-white font-semibold rounded-lg shadow-md hover:from-blue-600 hover:to-purple-600 transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-offset-2 text-base sm:text-lg"
          >
            View Detail
          </button>
        </div>
        <div className="inline-flex items-center space-x-2 text-white text-xs sm:text-sm">
          <div className="px-3 py-1 sm:px-5 sm:py-2 bg-blue-400 rounded-full animate-pulse">
            <span>Generated by AI Learning Analytics</span>
          </div>
        </div>
      </div>
    </div>
  );
}
